### ISSUE TITLE
Search locations

### ISSUE THREAD

**Issue by davidhedlund** [alaskalinuxuser/app_justcraigslist#5]
It would be nice to be able to search your location.

* Please change "Pick your city:" to "Pick your location:" because both cities and countries are on the list.

**Comment by alaskalinuxuser** [comment]
Yes, I need to find a better way to do this.

**Comment by alaskalinuxuser** [comment]
Okay, updated the city selection to include a search function. I just uploaded it to the play store, and am uploading the commit to github now.

**Comment by alaskalinuxuser** [comment]
Fixed with commit: https://github.com/alaskalinuxuser/app_justcraigslist/commit/a5a55fb94e179c9c14afa7398793633c607b9fe2

**Comment by davidhedlund** [comment]
@alaskalinuxuser Thank you.
